on:
  push:
    branches:
      - main
  pull_request:

name: Test Coveralls

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - name: npm install, make test-coverage
        run: |
          npm ci
          npm run coverage
      - uses: coverallsapp/github-action@v2
